[versions]
agp = "9.0.0"

android-compileSdk  = "36" #Android-16
android-targetSdk   = "34" #Android-14
android-minSdk      = "24" #Android-7
android-wear-minSdk = "26" #Android-8

kotlin = "2.3.10"
compose-plugin = "1.10.1"
kotlin-serialization = "1.10.0"
coroutines = "1.10.2"
viewmodel-compose = "2.9.6"
navigation-compose = "2.9.2"

androidx-activity-compose = "1.12.4"
coil = "3.3.0"
ktor = "3.4.0"
koin = "4.1.1"
koin-compose = "4.1.1"
paging-compose = "3.3.0-alpha02-0.5.1"
kermit-logger = "2.0.8"
build-konfig = "0.17.1"
play-services-wearable = "19.0.0"
compose-bom = "2026.02.00"
wear-compose-material3 = "1.5.6"
wear-compose-foundation = "1.5.6"
core-splashscreen = "1.2.0"
wearToolingPreview = "1.0.0"
core-ktx = "1.17.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"

[libraries]
kotlin-test                 = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit           = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-serialization       = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }


androidx-activity-compose   = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-bom                 = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui                  = { module = "androidx.compose.ui:ui" }
compose-ui-tooling          = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview  = { module = "androidx.compose.ui:ui-tooling-preview" }

# For navigation
navigation-compose          = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

# MVVM Compose
viewmodel-compose           = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }

kotlinx-coroutines-core     = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android  = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# coil3
coil-compose                = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor           = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# ktor
ktor-client-core            = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging         = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp          = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin          = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization          = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-negotiation            = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

#koin
koin-core                   = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test                   = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android                = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose                = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel      = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }

paging-compose              = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-compose" }

kermit-logger               = { module = "co.touchlab:kermit", version.ref = "kermit-logger" }

play-services-wearable      = { module = "com.google.android.gms:play-services-wearable", version.ref = "play-services-wearable" }

wear-compose-material3      = { module = "androidx.wear.compose:compose-material3", version.ref = "wear-compose-material3" }
wear-compose-foundation     = { module = "androidx.wear.compose:compose-foundation", version.ref = "wear-compose-foundation" }
wear-tooling-preview        = { module = "androidx.wear:wear-tooling-preview", version.ref = "wearToolingPreview" }
core-splashscreen           = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }

ui-test-manifest            = { module = "androidx.compose.ui:ui-test-manifest" }
ui-test-junit4              = { module = "androidx.compose.ui:ui-test-junit4" }
core-ktx                    = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
junit                       = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit     = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
espresso-core               = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

#[bundles]
#bundlesName = ["first-lib", "seconds-lib", ect]

[plugins]
androidApplication          = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatformLibrary  = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform         = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler            = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization         = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrainsCompose            = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
buildKonfig                 = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig" }